apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: payments-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-backend
  template:
    metadata:
      labels:
        app: payments-backend
    spec:
      containers:
        - name: backend
          image: payments-backend:local-v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: SERVER_PORT
              value: "8086"

            # ============================
            # MySQL Config (inside cluster)
            # ============================
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/payments?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

            # ============================
            # Redis Config (inside cluster)
            # ============================
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

            # ============================
            # Stripe Secrets
            # ============================
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: stripeApiKey

            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: stripeWebhookSecret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: payments-demo
spec:
  selector:
    app: payments-backend
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
